version: 0.2

# Test comment to verify CodePipeline source detection
phases:
  pre_build:
    commands:
      - echo Starting database migration at `date`
      - echo CLUSTER_NAME=$CLUSTER_NAME
      - echo TASK_DEFINITION=$TASK_DEFINITION
      - echo SUBNET_IDS=$SUBNET_IDS
      - echo SECURITY_GROUP_IDS=$SECURITY_GROUP_IDS
  build:
    commands:
      - echo Launching migration task...
      - TASK_ARN=$(aws ecs run-task --cluster $CLUSTER_NAME --task-definition $TASK_DEFINITION --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_IDS],securityGroups=[$SECURITY_GROUP_IDS],assignPublicIp=ENABLED}" --query 'tasks[0].taskArn' --output text)
      - echo Waiting for migration task to complete...
      - aws ecs wait tasks-stopped --cluster $CLUSTER_NAME --tasks $TASK_ARN
      - echo Getting task details...
      - TASK_STATUS=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].lastStatus' --output text)
      - TASK_EXIT_CODE=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].containers[0].exitCode' --output text)
      - echo Task Status is $TASK_STATUS
      - echo Exit Code is $TASK_EXIT_CODE
      - test "$TASK_STATUS" = "STOPPED"
      - test "$TASK_EXIT_CODE" = "0"
  post_build:
    commands:
      - echo Migration completed at `date`

artifacts:
  files:
    - task-arn.txt
  discard-paths: yes
